'use strict';

module.exports = {
    DIFFICULTY_BEGINNER: 0,
    DIFFICULTY_EASY: 1,
    DIFFICULTY_MEDIUM: 2,
    DIFFICULTY_HARD: 3,
    DIFFICULTY_EXPERT: 4,
    DIFFICULTY_EMPTY: 5,
    BOARD_SIZE: 9,
    EMPTY_CELL: 0,
};
